acme_security:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_blog:
    resource: "@AcmeBlogBundle/Resources/config/routing.yml"
    prefix:   /

acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
