acme_task_new:
    path:     /task/new
    defaults: { _controller: AcmeTaskBundle:Default:new }

acme_task_success:
    path:     /task/success
    defaults: { _controller: AcmeTaskBundle:Default:success }